version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: docker/dev.Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
    db:
        image: mysql:8
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata:
