version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    #volumes:
    #  - .:/var/www
    #  - ./storage:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel_network
  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysqldata:
